runtime: python
env: flex
manual_scaling:
  instances: 1
entrypoint: gunicorn -w 3 -k gevent -b :$PORT server.main:app
skip_files:
  - ^venv/
  - \.git/
  - node_modules/
  - __pycache__/

runtime_config:
  python_version: 3.5

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://site:password@/site?unix_socket=/cloudsql/elevated-agent-171907:us-west1:website-0

beta_settings:
  cloud_sql_instances: elevated-agent-171907:us-west1:website-0
